### PR TITLE
Add Merchant Fulfillment API

### PR DESCRIPTION
**Pull request by joeirimpan**

### CODE REVIEW

**Comment by gavargas22** [comment]
Any reason why the pull requests are not being accepted? I am just curious

**Comment by jaredkipe** [comment]
👍  This pull request has saved me a lot of time, but there are numerous problems...

There are inconsistent method signatures, specifically `dimensions_unit` is not in the method parameter list, but is needed.

Probably want to make `build_shipment_request_details` a private method like `_build_shipment_request_details` as you don't "optionally" take in data of this form. (though this would be nice to have the option to pass in a pre-built shipment_request_details object)

There are some inconsistent casing/capitalization/underscoring of various parameters like the "shape" of origin_address.  e.g. 'addressline1' is the key for 'AddressLine1' but then 'postal_code' is the key for 'PostalCode'.  Same for 'state'.

Probably want to indicate that 'dimensions' is a dictionary like object instead of tuple. 

Validation errors like the needed shape of the 'origin_address' in the api is like 'ShipmentRequestDetails.ShipFromAddress.Name' but implemented as 'ShipmentRequestDetails.Name'.

Potentially want to test for `dimensions_unit` like the test for `confirmation_type`
```
assert dimensions_unit in ['centimeters', 'inches']
```

Potentially want to cast any 'numeric' like type to str when building the shipping details, as its a common *gotcha*.

**Comment by joeirimpan** [comment]
@jaredkipe  Thanks for the very clear review. I have updated the code.

**Comment by czpython** [comment]
Thanks for the pr.
Closing as this project is no longer maintained.
Please head over to https://github.com/python-amazon-mws/python-amazon-mws.

**Pull request closed without merging**
